services:
  anisette:
    image: dadoum/anisette-v3-server
    expose:
      - "6969"

  web:
    image: nginx:alpine
    ports:
      - "80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx:/etc/nginx/conf.d:ro
