services:
  anisette:
    image: "dadoum/anisette-v3-server"
    expose:
      - "6969"

  web:
    image: "nginx:alpine"
    expose:
      - "80"
    labels:
      - "traefik.http.services.web.loadbalancer.server.port=80"
    volumes:
      - "./public:/usr/share/nginx/html:ro"
      - "./nginx:/etc/nginx/conf.d:ro"
