server {
  listen 80;

  location = /servers.json {
    root /usr/share/nginx/html;
    add_header Content-Type application/json;
  }

  location / {
    proxy_pass http://anisette:6969;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
